# Generated by Django 4.2 on 2025-08-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
