# Generated by Django 4.2 on 2025-08-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobDetails', '0002_mumbaijobs_punejobs_rename_job_hyderabadjobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HyderabadJobs',
            new_name='HyderabadJob',
        ),
        migrations.RenameModel(
            old_name='MumbaiJobs',
            new_name='MumbaiJob',
        ),
        migrations.RenameModel(
            old_name='PuneJobs',
            new_name='PuneJob',
        ),
    ]
