# Generated by Django 4.2 on 2025-09-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='action',
        ),
    ]
