# Generated by Django 4.2 on 2025-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mob_no',
            field=models.CharField(max_length=15),
        ),
    ]
