# Generated by Django 4.2 on 2025-08-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, verbose_name='Movie Name')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('main_hero', models.CharField(max_length=100, verbose_name='Main Hero')),
                ('main_heroine', models.CharField(max_length=100, verbose_name='Main Heroine')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating')),
            ],
        ),
    ]
