# Generated by Django 4.2 on 2025-08-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
